name: build_and_publish_lib
on:
  push:
    branches:
      - master
jobs:
  first_job:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Start
        uses: actions/checkout@master
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"
      - run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build
      - name: Publish
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
#          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
#          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Psigning.keyId=${SIGNING_KEYID} -Psigning.password=${SIGNING_PASSWORD}